### ISSUE TITLE
Preserve original header style and combine title into it

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#18]
Right now the sticky header uses the entire width on large displays, making it transition in a weird way. I think it should also combine the title into the header so that there's much less empty space. And if the title is too long to comfortably display, making it overflow like this: "Title  is very lo..."

Sticky header:
![image](https://user-images.githubusercontent.com/19501722/41316350-69636d26-6e92-11e8-9c78-0982cf2182c9.png)

Original header:
![image](https://user-images.githubusercontent.com/19501722/41316361-74aa8ca0-6e92-11e8-84d9-dc6323092a1d.png)

Proposed header (bad photoshop):
![image](https://user-images.githubusercontent.com/19501722/41316551-fa4c9754-6e92-11e8-951e-529efb3d6ada.png)

**Comment by theCrius** [comment]
I tried with that but we run into the problem of loooooooooong title. Any idea how to manage that?

**Comment by theCrius** [comment]
Ok, i completely missed the suggestion to truncate the title. I'll work on that.

**Comment by theCrius** [comment]
Included in latest release 0.8.4
