### ISSUE TITLE
[External Styles] Add a daily check to update the source code

### ISSUE THREAD

**Issue by theCrius** [theCrius/tildes-extended#2]
Instead of forcing the user to go into the settings and reimport the CSS from the external URL, just have a background script run once per day and pull the code automatically.

This way the author of the styles can have their users receive automatically the updated styles.

Need to be investigated.

**Comment by Bauke** [comment]
To extend on this issue, I think it would be nice if the URL we're using to import the styles from is saved inside the input box. This way you never have to navigate back to the URL you're getting the style from.

**Comment by theCrius** [comment]
The current behaviour *should be* that unless you deactivate the feature, the URL input keep the url you inserted.
If you deactivate the feature, it cleans both the URL field and the source code stored in the browser storage.
I thought about leaving the URL anyway but I wanted to be consistent with what the user see and what is actually stored.

**Comment by Bauke** [comment]
Hm, in that case it doesn't work for me. I add the link to the input box, click save and then refresh the page/reopen the settings and the link is gone. The feature is still activated and the theme still works.

**Comment by theCrius** [comment]
Just to mention that the URL not appearing when it should have has been fixed some commits ago.
https://github.com/theCrius/tildes-extended/commit/2f74e42bf6a506ba115935a2655aaff12c551cd2

Also the implementation of the multiple css and custom css has been deployed on develop and retain the same bugfix so everything should be good.

After the re-design of the option page I'll try and focus on a daily check as per issue. I'll have to mess with background scripts.
