### ISSUE TITLE
[Feature Request] Randomly changing Tildes logo

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#21]
Originally from [Ark](https://tildes.net/user/Ark) posted [here](https://tildes.net/~tildes/27j#comment-nqg), not specifically requested to be added here but I think it would be pretty neat.

> For example, if the upper left logo was replaced with just the symbol itself, everytime the page refreshes it could change to a random colour to keep it fresh?

Basically replace the Tildes header logo with the character `~` and make it change color each refresh.

**Comment by theCrius** [comment]
I think this could be a first "cool thing" to have in a "Miscellaneous" setting.

Things that are just small funny / cool things to have. Feel free to go ahead with it and run a pull request when you're satisfied 👍

**Comment by theCrius** [comment]
Included in https://github.com/theCrius/tildes-extended/commit/b515fb3a9e54a13fbfb1a798485920cb34d43fc5
