### ISSUE TITLE
Add enabled indicator to feature list

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#22]
Would be nice to get a complete overview of which feature is enabled quickly. A simple pill badge with a checkmark inside would suffice.

Relevant links:
* [List group with badges](https://getbootstrap.com/docs/4.1/components/list-group/#with-badges)
* [Pill badges](https://getbootstrap.com/docs/4.1/components/badge/#pill-badges)

**Comment by theCrius** [comment]
Yep I agree.

You can take this one by yourself I think, just remember to:

- branch out from develop
- create a branch with the name features/something_something
- once finished, create a pull request for the branch, to merge back into develop

If you need any help with git or the js part, let me know :)

**Comment by theCrius** [comment]
Included in latest release 0.8.4
