### ISSUE TITLE
Sticky header cuts off part of comments when using "next new comment"

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#24]
When using "next new comment":

![image](https://user-images.githubusercontent.com/19501722/41411913-b46460e4-6fde-11e8-822f-bd5865bf06ab.png)

Full comment:

![image](https://user-images.githubusercontent.com/19501722/41411940-c650bbfe-6fde-11e8-918a-f0905a2580ed.png)

**Comment by theCrius** [comment]
Right, I even noticed that and forgot to address the issue.

I'll fix it in the next release :)

**Comment by theCrius** [comment]
Will be included in the next release.
