### ISSUE TITLE
[Custom Styles] User style not loaded if there are no external styles

### ISSUE THREAD

**Issue by theCrius** [theCrius/tildes-extended#27]
## Expected Behavior

Applying user style only

## Current Behavior

User style are not applied if there aren't external styles.

## Steps to Reproduce

1. Enable custom styles
2. Write something like `body {background-color: red; }` in the user style textarea.
3. Loat a tildes.net page, the style will not be applied

## Environment

Not relevant

## Additional notes

In the custom style <style> there is an `undefined`. Probably some typo or logic error in the concatenation of styles.

**Comment by Bauke** [comment]
Took a quick look at the options and I think this is where it goes wrong

https://github.com/theCrius/tildes-extended/blob/d6648d90d291fde9d733364efcd02cc530951d25/src/scripts/options.js#L159-L162

It doesn't check whether remoteSource is defined, it just adds it. That's where the undefined comes from. 

remoteSource's definition:

https://github.com/theCrius/tildes-extended/blob/d6648d90d291fde9d733364efcd02cc530951d25/src/scripts/options.js#L151-L153

**Comment by theCrius** [comment]
Good catch, feel free to fix it if you feel like it, otherwise I'll do it later today :)

**Comment by theCrius** [comment]
Fixed in https://github.com/theCrius/tildes-extended/commit/f65153e7f3475470722e03142882d8e66420fe30

Will be in the next release (approx this weekend)
