### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#3]
I'm not sure if I understand the functionality of the custom CSS properly or if it just doesn't work with how I applied it but I tried activating my [Dracula theme](https://gitlab.com/Bauke/TildesDracula/raw/master/css/tildes.css) with the raw link and it doesn't work. There's a few errors being reported in the browser console so it could be that one of my extensions is causing it to not work but I'll report it here just it case.

![Console errors](https://user-images.githubusercontent.com/19501722/41170591-384f8c4e-6b4d-11e8-983b-290f3abd4b50.png)

![Tildes settings](https://user-images.githubusercontent.com/19501722/41170609-480985e0-6b4d-11e8-9404-9710f3ce11fd.png)

If you want me to I can list all my Firefox extensions. I'll also try disabling them and seeing if I can find which one is causing the problem (if at all).

Edit: issue persists with all extensions disabled.

**Comment by Bauke** [comment]
Oh, just got the update and I disabled the CSP value and now it works! Guess I got a little too eager. (^:

**Comment by theCrius** [comment]
Yes, sorry, in the next version I specified in firefox settings that you need to disable that flag. It's a temporary workaround until either mozilla fix some SCP weirdness or I find a way of dealing with it.

Right now is not a priority but I will come back to it at some point :)
