### ISSUE TITLE
Include version number somewhere in the options

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#33]
## Is your feature request related to a problem? Please describe.

Right now it's "hard" to figure out what version you're on. On Chrome you just have to right-click -> Manage Extensions but on Firefox you have to navigate to Add-ons, find Tildes Extended and click on More.

## (optional) Describe the solution you'd like

Include TE version number somewhere in the options page. Maybe in the header?

**Comment by theCrius** [comment]
Done by adding  "web_accessible_resources" to manifest.json. Adding to the accessible resource, the manifest.json itself and from now on, all the json files in /data/ (a new folder). Updated gulp accordingly.
