### ISSUE TITLE
Custom CSS only applies to tildes.net

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#4]
Back again so quickly after previous issue, this time to report that custom css doesn't work on sites like [Docs](https://docs.tildes.net/) and [Blog](https://blog.tildes.net/).

Edit: for some reason when I go into ~test it also doesn't work, I'm not sure if this is intentional though.

**Comment by Bauke** [comment]
Yes, the CSS I'm loading is from [here](https://gitlab.com/Bauke/TildesDracula/raw/master/css/tildes.css) and I'm using Firefox. I was working on adding the docs and blog styles earlier so that's why I noticed.

**Comment by theCrius** [comment]
Damn, ~test seems to work for me, I hate when errors are not consistent.

![image](https://user-images.githubusercontent.com/2202141/41180134-231e421c-6b65-11e8-9c5a-30d8ef6cfd7d.png)

I found a weird bug on the CSS loading this morning and I had to fix it a couple of time. Can you try do the following?

- Remove the extension & install it back
- In the setting page. Enable the CSS feature but leave the field empty. This should remove the CSS injected. To be sure, reload a tilde.net tab and you should see the default theme.
- Add the custom theme back and save.
- Try and reload tildes.net again and go into ~test

Let me know if the issue persist and if that's the case if there is anything in the developer console! :)

**Comment by Bauke** [comment]
Alright so I just did everything you said, plus I even tried it on Chrome and get this: it works just fine on Chrome and on Firefox when I'm in your thread... But not on the topic listings

![image](https://user-images.githubusercontent.com/19501722/41180765-9807402e-6b6f-11e8-8d4f-738b154de20d.png)

**Comment by theCrius** [comment]
I keep getting it working on ~test... I don't know how to fix it if I can't reproduce the issue :(

Anyway, I've extended the script to works on any subdomain of tildes.
I'm gonna work on another issue (the white theme support for the tags) and will release an update in a coupe of hours.

These are on firefox:

![image](https://user-images.githubusercontent.com/2202141/41181396-490745f6-6b69-11e8-9c20-a83dfdc9f08c.png)

![image](https://user-images.githubusercontent.com/2202141/41181406-5a87d2b4-6b69-11e8-8ace-d1dac54a0acd.png)

**Comment by Bauke** [comment]
Yeah, that's fine. Feel free to close this issue if you've fixed the domain thing. I usually use Stylus to load my styles anyways and that works on ~test fine. If it'll affect another user they can just report it again and then we might be able to figure it out.

**Comment by theCrius** [comment]
Yep, if others report the issue let's open a new one :)

**Comment by Bauke** [comment]
I just updated my theme a bunch and it seems ~test works just fine again. I have no idea how this suddenly got fixed but just thought I should let you know.
