### ISSUE TITLE
Fixed headerbar includes non-main headlines

### ISSUE THREAD

**Issue by deingithub** [theCrius/tildes-extended#44]
## Expected Behavior
The fixed headerbar should probably only show the topic title, not other headings in the comment section.

## Current Behavior
It appends all h1 elements to the headerbar text, in the screenshotted case from [this comment](https://tildes.net/~comp/7i7/what_editor_do_you_use#comment-22rj) 

## Screenshots
https://screenshots.firefox.com/FFwAJh8nWfVuuhtH/tildes.net

## Steps to Reproduce
1. Enable fixed headerbar in settings
2. Visit https://tild.es/7i7
3. Scroll down

## Environment
OS openSUSE Tumbleweed Snapshot 20181224-0  
Browser Firefox 64.0

## Additional notes
n/a

**Comment by Bauke** [comment]
Uploaded the fixed version (0.9.2).
