### ISSUE TITLE
Change default label color based on user-selected theme

### ISSUE THREAD

**Issue by arghdos** [theCrius/tildes-extended#5]
Migrated from [here](https://tildes.net/~tildes/1y8/repost_extension_tildes_extended#comment-kgc)

**Comment by theCrius** [comment]
Quoting the link to remind me of the context:

> My only nit to pick thus far is that the blank label box next to usernames is rather ugly (shrug), but on the other hand I can now tag you as TES :P
> 
> edit: it looks much better on a username in a comment (where it's got a background grey bar) and less good next to the submitter's username

**Comment by theCrius** [comment]
Could you post a screenshot of what you refer to as well? You can just take a screenshot, click on the comment box here and paste it. The site will do the rest (you don't need to host it somewhere first).

**Comment by arghdos** [comment]
![image](https://user-images.githubusercontent.com/6463881/41179672-8480b4da-6b39-11e8-92d6-c110c0c73444.png)

Empty tag box for OP, v.s., on a comment backdrop:

![image](https://user-images.githubusercontent.com/6463881/41179711-a4ee36ac-6b39-11e8-8c28-3e243bd332c6.png)

p.s., I didn't know you could copy-paste directly into GH!  Neat!

**Comment by theCrius** [comment]
Yep just tested.  The current one is fine for the "dark" themes (both).
I need to create a style for the "bright" themes. It will work for both.

Thanks for the screenshots :)

**Comment by arghdos** [comment]
@theCrius it might be as simple as flipping the color of the "+" sign in the empty label box depending on if the theme is light or dark

**Comment by theCrius** [comment]
Just finished. The label check its own background now and adapt the text color to white or black. This will also allow for light-colored backgrounds for labels but it's something that I'll implement later on i think (something like a wheel of colors)
