### ISSUE TITLE
User Labels - Voting a comment make the labels disappear

### ISSUE THREAD

**Issue by theCrius** [theCrius/tildes-extended#8]
Report from the user [apoctr](https://tildes.net/~tildes/1y8/repost_extension_tildes_extended#comment-kev):

> I think I've found a bug - if you vote on the comment of someone you've labelled, their label disappears.

Apparently whenever a vote is casted, the whole comment is being sent back as response instead of just a json data that update the view.

![image](https://user-images.githubusercontent.com/2202141/41183040-65f053a4-6b70-11e8-9c1b-55a2deb46d18.png)

I suppose I can try and intercept the click on the vote button and rebuild the label for that comment.

**Comment by theCrius** [comment]
As a workaround I'm refreshing the labels after 500msec for now.
Not really a solution I'm proud of. What I would have done is to listen for XHR requests and detect a response received but apparently either it doesn't work with browser extension injected code or tildes.net use masked request.

It's a weird way, from tildes, to reload a whole object anyway when simply voting. I would have expected at most that the object received back was the 'vote button' or just the updated vote counts.

**Comment by odensc** [comment]
@theCrius You can use `MutationObserver` to listen for updates to the DOM of the comment. I could submit a PR for this if you're not familiar with the API.

**Comment by theCrius** [comment]
I didn't think about the MutationObserver... that'll teach me to not code late at night :(

However I never used it but I created this project to try stuff I never used! I'll give it a look and update this issue in case I've issue, thanks!

**Comment by theCrius** [comment]
Mhm, something's not right.

I've wrote a basic observer to detect changes:

```
const clog = console.log.bind(console);
const MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver;

const observer = new MutationObserver(mutations => {
  clog('something changed', mutations);
});

observer.observe(document.body, {
	attributes: true,
	childList: true,
	characterData: true
});
```
But while it detect changes on the page load, it doesn't detect changes when I click on a vote button.

If you feel like wasting some time on it, I'll appreciate a pull request (or if you can point out where I'm doing it wrong as well!)

**Comment by odensc** [comment]
I'll take a look.

**Comment by theCrius** [comment]
https://github.com/theCrius/tildes-extended/commit/31bec8a67c583cc808edcf2c7522341bdcfba39f

Clean up and deal with missing node to observe (for page with no comments)
