### ISSUE TITLE
Remove !important from text-dark/light

### ISSUE THREAD

**Issue by Bauke** [theCrius/tildes-extended#9]
Any chance the `!important` could be removed from here

https://github.com/theCrius/tildes-extended/blob/cea2065a7095a2dd9210e5fe146c5b84c5ee5ffa/src/styles/users-label.scss#L9-L17

The `!important` makes it so it overrides any possible theming and I don't think you even need to use it here.

I could send a PR if you want.

**Comment by theCrius** [comment]
Sure, I forgot to remove it after some testing!

I'll release an hotfix for this as it surely block you're work on themes as well.
